name: Build & Deploy React (Docker)

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: [self-hosted, linux]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Stop existing container (if any)
        run: |
          docker stop react-app || true
          docker rm react-app || true

      - name: Build React Docker image
        run: docker build -t react-app:latest .

      - name: Run React container
        run: |
          docker run -d \
            --name react-app \
            -p 80:80 \
            --restart always \
            react-app:latest
